import { NextResponse } from "next/server";
import { PDFDocument, rgb } from "pdf-lib";
import fontkit from "@pdf-lib/fontkit";
import { readFile } from "node:fs/promises";
import { join } from "node:path";
import { createClient } from "@/lib/supabase/server";

const PAGE = { width: 595.2756, height: 841.8898 };
const safe = (v:unknown) => String(v ?? "").replace(/[\r\n\t]+/g," ").trim();
const money = (v:number) => "₹" + Math.round(v).toLocaleString("en-IN") + "/-";
const dateLabel = (v?:string|null) => {
  if(!v) return "—";
  const d=new Date(v+"T00:00:00");
  return Number.isNaN(d.getTime()) ? v : d.toLocaleDateString("en-IN",{day:"2-digit",month:"short",year:"numeric"});
};

export async function GET(_request:Request, context:{params:Promise<{id:string}>}) {
  const {id}=await context.params;
  const supabase=await createClient();
  const {data:user}=await supabase.auth.getUser();
  if(!user.user) return new NextResponse("Unauthorized",{status:401});

  const {data:client,error:clientError}=await supabase.from("clients").select("*").eq("id",id).maybeSingle();
  if(clientError||!client) return new NextResponse("Client not found",{status:404});

  const {data:invoices,error}=await supabase
    .from("invoices")
    .select("id,invoice_number,issue_date,due_date,status,invoice_contents(*),payments(*)")
    .eq("client_id",id)
    .order("issue_date",{ascending:true});
  if(error) return new NextResponse("Could not load statement",{status:500});

  const rows=(invoices??[]).map((invoice:any)=>{
    const total=(invoice.invoice_contents??[]).reduce((s:number,c:any)=>s+(c.priced?Number(c.amount??Number(c.quantity??1)*Number(c.rate??0)):0),0);
    const paid=(invoice.payments??[]).reduce((s:number,p:any)=>s+Number(p.amount||0),0);
    return {invoice,total,paid,balance:Math.max(total-paid,0)};
  });
  const billed=rows.reduce((s,r)=>s+r.total,0);
  const collected=rows.reduce((s,r)=>s+r.paid,0);
  const outstanding=Math.max(billed-collected,0);

  const pdf=await PDFDocument.create();
  pdf.registerFontkit(fontkit);
  const regular=await pdf.embedFont(await readFile(join(process.cwd(),"public","fonts","Geist-Regular.ttf")),{subset:true});
  const bold=await pdf.embedFont(await readFile(join(process.cwd(),"public","fonts","Geist-SemiBold.ttf")),{subset:true});
  const mono=await pdf.embedFont(await readFile(join(process.cwd(),"public","fonts","GeistMono-Regular.ttf")),{subset:true});
  const black=rgb(0,0,0);
  let page=pdf.addPage([PAGE.width,PAGE.height]);
  let y=780;
  const text=(v:string,x:number,yy:number,font:any,size=9)=>page.drawText(safe(v),{x,y:yy,font,size,color:black});
  text("ACCOUNT STATEMENT",62,y,bold,16); y-=24;
  text(safe(client.legal_name||client.name),62,y,bold,11); y-=15;
  if(client.email) { text(safe(client.email),62,y,regular,9); y-=14; }
  if(client.gstin) { text("GSTIN: "+safe(client.gstin),62,y,regular,9); y-=14; }
  y-=14;
  page.drawLine({start:{x:62,y},end:{x:533,y},thickness:.7,color:black}); y-=28;

  text("BILLED",62,y,bold,8); text("COLLECTED",190,y,bold,8); text("OUTSTANDING",330,y,bold,8);
  y-=17; text(money(billed),62,y,mono,13); text(money(collected),190,y,mono,13); text(money(outstanding),330,y,mono,13);
  y-=34;

  const drawHeader=()=>{
    text("INVOICE",62,y,bold,8); text("DATE",155,y,bold,8); text("TOTAL",270,y,bold,8); text("PAID",365,y,bold,8); text("BALANCE",455,y,bold,8);
    y-=10; page.drawLine({start:{x:62,y},end:{x:533,y},thickness:.6,color:black}); y-=18;
  };
  drawHeader();

  for(const row of rows){
    if(y<92){ page=pdf.addPage([PAGE.width,PAGE.height]); y=780; drawHeader(); }
    text("#"+safe(row.invoice.invoice_number),62,y,mono,8);
    text(dateLabel(row.invoice.issue_date),155,y,regular,8);
    text(money(row.total),270,y,mono,8);
    text(money(row.paid),365,y,mono,8);
    text(money(row.balance),455,y,mono,8);
    y-=18;
  }

  if(!rows.length) text("No invoices recorded for this client.",62,y,regular,9);
  y=58;
  page.drawLine({start:{x:62,y:76},end:{x:533,y:76},thickness:.5,color:black});
  text("Statement generated by MinBooks.",62,y,regular,8);
  const bytes=await pdf.save();
  return new NextResponse(bytes,{headers:{
    "Content-Type":"application/pdf",
    "Content-Disposition":`attachment; filename="Statement-${safe(client.name||"Client").replace(/[^a-z0-9]+/gi,"-")}.pdf"`,
    "Cache-Control":"private, no-store"
  }});
}
