import { NextRequest, NextResponse } from "next/server";
import { PDFDocument, rgb } from "pdf-lib";
import fontkit from "@pdf-lib/fontkit";
import { readFile } from "node:fs/promises";
import { join } from "node:path";
import { createClient } from "@/lib/supabase/server";
import { hashPortalSession } from "@/lib/portal/auth";

const safe=(v:unknown)=>String(v??"").replace(/[\r\n\t]+/g," ").trim();
const money=(v:number)=>"₹"+Math.round(v).toLocaleString("en-IN")+"/-";
const date=(v?:string|null)=>v?new Date(v+"T00:00:00").toLocaleDateString("en-IN",{day:"2-digit",month:"long",year:"numeric"}):"—";

export async function GET(request:NextRequest,context:{params:Promise<{slug:string;id:string}>}){
  const {slug,id}=await context.params;
  const session=request.cookies.get("portal_session")?.value||"";
  if(!slug||!session)return new NextResponse("Authentication required",{status:401});
  const supabase=await createClient();
  const {data,error}=await supabase.rpc("get_client_portal",{p_slug:slug,p_session:hashPortalSession(session)});
  if(error||!data)return new NextResponse("Portal session expired",{status:401});
  const portal:any=data;
  const payment=(portal.payments||[]).find((p:any)=>p.id===id);
  if(!payment)return new NextResponse("Payment not found",{status:404});
  const pdf=await PDFDocument.create();pdf.registerFontkit(fontkit);
  const regular=await pdf.embedFont(await readFile(join(process.cwd(),"public","fonts","Geist-Regular.ttf")),{subset:true});
  const bold=await pdf.embedFont(await readFile(join(process.cwd(),"public","fonts","Geist-SemiBold.ttf")),{subset:true});
  const mono=await pdf.embedFont(await readFile(join(process.cwd(),"public","fonts","GeistMono-Regular.ttf")),{subset:true});
  const black=rgb(0,0,0);const page=pdf.addPage([595.2756,841.8898]);let y=780;
  const text=(v:string,x:number,yy:number,font:any,size=9)=>page.drawText(safe(v),{x,y:yy,font,size,color:black});
  text("PAYMENT RECEIPT",62,y,bold,16);y-=25;text(safe(portal.organization?.name||""),62,y,bold,10);y-=34;page.drawLine({start:{x:62,y},end:{x:533,y},thickness:.7,color:black});y-=30;
  text("RECEIVED FROM",62,y,bold,8);y-=18;text(safe(portal.client?.legal_name||portal.client?.name||"Client"),62,y,regular,10);y-=34;
  text("AMOUNT RECEIVED",62,y,bold,8);y-=18;text(money(Number(payment.amount||0)),62,y,mono,20);y-=40;
  [["Invoice","#"+safe(payment.invoice_number)],["Payment date",date(payment.payment_date)],["Method",String(payment.method||"").replaceAll("_"," ")],["Reference",payment.reference||"—"]].forEach(([label,value])=>{text(label,62,y,bold,8);text(String(value),180,y,regular,9);y-=22;});
  y=58;text("Receipt generated by MinBooks.",62,y,regular,8);
  const bytes=await pdf.save();
  return new NextResponse(bytes,{headers:{"Content-Type":"application/pdf","Content-Disposition":`attachment; filename="Receipt-${safe(payment.invoice_number||"payment")}-${id.slice(0,8)}.pdf"`,"Cache-Control":"private, no-store"}});
}
