import { NextRequest, NextResponse } from "next/server";
import { PDFDocument, rgb } from "pdf-lib";
import fontkit from "@pdf-lib/fontkit";
import { readFile } from "node:fs/promises";
import { join } from "node:path";
import { createClient } from "@/lib/supabase/server";
import { hashPortalSession } from "@/lib/portal/auth";

const safe=(v:unknown)=>String(v??"").replace(/[\r\n\t]+/g," ").trim();
const money=(v:number)=>"₹"+Math.round(v).toLocaleString("en-IN")+"/-";
const date=(v?:string|null)=>v?new Date(v+"T00:00:00").toLocaleDateString("en-IN",{day:"2-digit",month:"short",year:"numeric"}):"—";

export async function GET(request:NextRequest){
  const slug=request.nextUrl.pathname.split("/").filter(Boolean).at(-2)||"";
  const period=request.nextUrl.searchParams.get("period")||"all";
  const session=request.cookies.get("portal_session")?.value||"";
  if(!slug||!session)return new NextResponse("Authentication required",{status:401});
  const supabase=await createClient();
  const {data,error}=await supabase.rpc("get_client_portal",{p_slug:slug,p_session:hashPortalSession(session)});
  if(error||!data)return new NextResponse("Portal session expired",{status:401});
  const portal:any=data;
  const invoices=(portal.invoices||[]).filter((i:any)=>{
    if(period==="all")return true;
    const d=new Date(i.issue_date+"T00:00:00"),now=new Date(),end=new Date(now.getFullYear(),now.getMonth()+1,0);
    if(period==="month")return d.getFullYear()===now.getFullYear()&&d.getMonth()===now.getMonth();
    if(period==="3months")return d>=new Date(now.getFullYear(),now.getMonth()-2,1)&&d<=end;
    if(period==="6months")return d>=new Date(now.getFullYear(),now.getMonth()-5,1)&&d<=end;
    const fy=new Date(now.getMonth()>=3?now.getFullYear():now.getFullYear()-1,3,1);
    return d>=fy&&d<=new Date(fy.getFullYear()+1,2,31);
  });
  const billed=invoices.reduce((s:number,i:any)=>s+Number(i.total||0),0);
  const paid=invoices.reduce((s:number,i:any)=>s+Number(i.paid||0),0);
  const balance=invoices.reduce((s:number,i:any)=>s+Number(i.balance||0),0);
  const pdf=await PDFDocument.create();pdf.registerFontkit(fontkit);
  const regular=await pdf.embedFont(await readFile(join(process.cwd(),"public","fonts","Geist-Regular.ttf")),{subset:true});
  const bold=await pdf.embedFont(await readFile(join(process.cwd(),"public","fonts","Geist-SemiBold.ttf")),{subset:true});
  const mono=await pdf.embedFont(await readFile(join(process.cwd(),"public","fonts","GeistMono-Regular.ttf")),{subset:true});
  const black=rgb(0,0,0);let page=pdf.addPage([595.2756,841.8898]);let y=780;
  const text=(v:string,x:number,yy:number,font:any,size=9)=>page.drawText(safe(v),{x,y:yy,font,size,color:black});
  text("ACCOUNT STATEMENT",62,y,bold,16);y-=24;text(safe(portal.organization?.name||""),62,y,bold,10);y-=16;text(safe(portal.client?.legal_name||portal.client?.name||"Client"),62,y,regular,10);y-=28;page.drawLine({start:{x:62,y},end:{x:533,y},thickness:.7,color:black});y-=26;
  text("BILLED",62,y,bold,8);text("COLLECTED",190,y,bold,8);text("OUTSTANDING",330,y,bold,8);y-=17;text(money(billed),62,y,mono,12);text(money(paid),190,y,mono,12);text(money(balance),330,y,mono,12);y-=32;
  text("INVOICE",62,y,bold,8);text("DATE",160,y,bold,8);text("TOTAL",280,y,bold,8);text("PAID",370,y,bold,8);text("BALANCE",455,y,bold,8);y-=12;page.drawLine({start:{x:62,y},end:{x:533,y},thickness:.6,color:black});y-=18;
  for(const i of invoices){if(y<90){page=pdf.addPage([595.2756,841.8898]);y=780;}text("#"+safe(i.invoice_number),62,y,mono,8);text(date(i.issue_date),160,y,regular,8);text(money(Number(i.total||0)),280,y,mono,8);text(money(Number(i.paid||0)),370,y,mono,8);text(money(Number(i.balance||0)),455,y,mono,8);y-=18;}
  y=58;text("Secure client account · Statement generated by MinBooks.",62,y,regular,8);
  const bytes=await pdf.save();
  return new NextResponse(bytes,{headers:{"Content-Type":"application/pdf","Content-Disposition":`attachment; filename="Statement-${safe(portal.client?.name||"Client").replace(/[^a-z0-9]+/gi,"-")}.pdf"`,"Cache-Control":"private, no-store"}});
}
